-- Phase 3: Grievance Submission

-- 1. Create Enums
CREATE TYPE public.grievance_status AS ENUM ('SUBMITTED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED');

-- 2. Create Sequence for Grievance ID
CREATE SEQUENCE IF NOT EXISTS public.grievance_seq START 1;

-- 3. Create Grievances Table
CREATE TABLE public.grievances (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    grievance_number TEXT UNIQUE, -- Generated by trigger
    citizen_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    department_id UUID NOT NULL REFERENCES public.departments(id),
    category_id UUID NOT NULL REFERENCES public.categories(id),
    state TEXT NOT NULL,
    district TEXT NOT NULL,
    status public.grievance_status DEFAULT 'SUBMITTED'::public.grievance_status NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on grievances
ALTER TABLE public.grievances ENABLE ROW LEVEL SECURITY;

-- Grievances Policies
CREATE POLICY "Citizens can insert their own grievances."
    ON public.grievances FOR INSERT
    WITH CHECK ( auth.uid() = citizen_id );

CREATE POLICY "Citizens can view their own grievances."
    ON public.grievances FOR SELECT
    USING ( auth.uid() = citizen_id );

-- 4. Trigger to Generate Grievance ID (GRV-YYYY-XXXXXX)
CREATE OR REPLACE FUNCTION public.set_grievance_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.grievance_number := 'GRV-' || TO_CHAR(NOW(), 'YYYY') || '-' || LPAD(nextval('public.grievance_seq')::TEXT, 6, '0');
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_grievance_insert
    BEFORE INSERT ON public.grievances
    FOR EACH ROW EXECUTE FUNCTION public.set_grievance_number();

-- 5. Create Grievance Status History Table
CREATE TABLE public.grievance_status_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    grievance_id UUID NOT NULL REFERENCES public.grievances(id) ON DELETE CASCADE,
    status public.grievance_status NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on history
ALTER TABLE public.grievance_status_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Citizens can view their own grievance history."
    ON public.grievance_status_history FOR SELECT
    USING ( 
        EXISTS (
            SELECT 1 FROM public.grievances g 
            WHERE g.id = grievance_status_history.grievance_id AND g.citizen_id = auth.uid()
        )
    );

-- Trigger to insert initial status history
CREATE OR REPLACE FUNCTION public.log_initial_grievance_status()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.grievance_status_history (grievance_id, status)
    VALUES (NEW.id, NEW.status);
    RETURN NEW;
END;
$$;

CREATE TRIGGER on_grievance_created
    AFTER INSERT ON public.grievances
    FOR EACH ROW EXECUTE FUNCTION public.log_initial_grievance_status();

-- 6. Create Grievance Attachments Table
CREATE TABLE public.grievance_attachments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    grievance_id UUID NOT NULL REFERENCES public.grievances(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on attachments
ALTER TABLE public.grievance_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Citizens can insert attachments for their own grievances."
    ON public.grievance_attachments FOR INSERT
    WITH CHECK ( 
        EXISTS (
            SELECT 1 FROM public.grievances g 
            WHERE g.id = grievance_id AND g.citizen_id = auth.uid()
        )
    );

CREATE POLICY "Citizens can view attachments for their own grievances."
    ON public.grievance_attachments FOR SELECT
    USING ( 
        EXISTS (
            SELECT 1 FROM public.grievances g 
            WHERE g.id = grievance_id AND g.citizen_id = auth.uid()
        )
    );

-- 7. Supabase Storage Setup (Buckets and Policies)
-- Insert bucket if it doesn't exist (public = false means private bucket)
INSERT INTO storage.buckets (id, name, public)
VALUES ('grievance_attachments', 'grievance_attachments', false)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
-- 1. Allow authenticated users to upload files to their own folder (folder name = user ID)
CREATE POLICY "Citizens can upload attachments to their folder"
    ON storage.objects FOR INSERT
    WITH CHECK (
        bucket_id = 'grievance_attachments' 
        AND auth.role() = 'authenticated'
        AND (storage.foldername(name))[1] = auth.uid()::text
    );

-- 2. Allow authenticated users to view/download files from their own folder
CREATE POLICY "Citizens can view their own attachments"
    ON storage.objects FOR SELECT
    USING (
        bucket_id = 'grievance_attachments' 
        AND auth.role() = 'authenticated'
        AND (storage.foldername(name))[1] = auth.uid()::text
    );
