-- Phase 19: Expanded Onboarding and Location Data

-- 1. Create states table
CREATE TABLE public.states (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    country TEXT DEFAULT 'India' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.states ENABLE ROW LEVEL SECURITY;
CREATE POLICY "States are viewable by everyone" ON public.states FOR SELECT USING (true);

-- 2. Create districts table
CREATE TABLE public.districts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    state_id UUID NOT NULL REFERENCES public.states(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(state_id, name)
);

-- Enable RLS
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Districts are viewable by everyone" ON public.districts FOR SELECT USING (true);

-- 3. Modify profiles table
ALTER TABLE public.profiles
ADD COLUMN gender TEXT CHECK (gender IN ('Male', 'Female', 'Transgender')),
ADD COLUMN address_line TEXT,
ADD COLUMN sub_locality TEXT,
ADD COLUMN country TEXT DEFAULT 'India',
ADD COLUMN state_id UUID REFERENCES public.states(id) ON DELETE SET NULL,
ADD COLUMN district_id UUID REFERENCES public.districts(id) ON DELETE SET NULL,
ADD COLUMN pincode TEXT,
ADD COLUMN landline_phone TEXT;

-- 4. Seed India Data
-- Data source: https://github.com/sab99r/Indian-States-And-Districts
DO $$
DECLARE
    state_0_id UUID;
    state_1_id UUID;
    state_2_id UUID;
    state_3_id UUID;
    state_4_id UUID;
    state_5_id UUID;
    state_6_id UUID;
    state_7_id UUID;
    state_8_id UUID;
    state_9_id UUID;
    state_10_id UUID;
    state_11_id UUID;
    state_12_id UUID;
    state_13_id UUID;
    state_14_id UUID;
    state_15_id UUID;
    state_16_id UUID;
    state_17_id UUID;
    state_18_id UUID;
    state_19_id UUID;
    state_20_id UUID;
    state_21_id UUID;
    state_22_id UUID;
    state_23_id UUID;
    state_24_id UUID;
    state_25_id UUID;
    state_26_id UUID;
    state_27_id UUID;
    state_28_id UUID;
    state_29_id UUID;
    state_30_id UUID;
    state_31_id UUID;
    state_32_id UUID;
    state_33_id UUID;
    state_34_id UUID;
BEGIN
    INSERT INTO public.states (name) VALUES ('Andhra Pradesh') RETURNING id INTO state_0_id;
    INSERT INTO public.states (name) VALUES ('Arunachal Pradesh') RETURNING id INTO state_1_id;
    INSERT INTO public.states (name) VALUES ('Assam') RETURNING id INTO state_2_id;
    INSERT INTO public.states (name) VALUES ('Bihar') RETURNING id INTO state_3_id;
    INSERT INTO public.states (name) VALUES ('Chandigarh (UT)') RETURNING id INTO state_4_id;
    INSERT INTO public.states (name) VALUES ('Chhattisgarh') RETURNING id INTO state_5_id;
    INSERT INTO public.states (name) VALUES ('Dadra and Nagar Haveli (UT)') RETURNING id INTO state_6_id;
    INSERT INTO public.states (name) VALUES ('Daman and Diu (UT)') RETURNING id INTO state_7_id;
    INSERT INTO public.states (name) VALUES ('Delhi (NCT)') RETURNING id INTO state_8_id;
    INSERT INTO public.states (name) VALUES ('Goa') RETURNING id INTO state_9_id;
    INSERT INTO public.states (name) VALUES ('Gujarat') RETURNING id INTO state_10_id;
    INSERT INTO public.states (name) VALUES ('Haryana') RETURNING id INTO state_11_id;
    INSERT INTO public.states (name) VALUES ('Himachal Pradesh') RETURNING id INTO state_12_id;
    INSERT INTO public.states (name) VALUES ('Jammu and Kashmir') RETURNING id INTO state_13_id;
    INSERT INTO public.states (name) VALUES ('Jharkhand') RETURNING id INTO state_14_id;
    INSERT INTO public.states (name) VALUES ('Karnataka') RETURNING id INTO state_15_id;
    INSERT INTO public.states (name) VALUES ('Kerala') RETURNING id INTO state_16_id;
    INSERT INTO public.states (name) VALUES ('Lakshadweep (UT)') RETURNING id INTO state_17_id;
    INSERT INTO public.states (name) VALUES ('Madhya Pradesh') RETURNING id INTO state_18_id;
    INSERT INTO public.states (name) VALUES ('Maharashtra') RETURNING id INTO state_19_id;
    INSERT INTO public.states (name) VALUES ('Manipur') RETURNING id INTO state_20_id;
    INSERT INTO public.states (name) VALUES ('Meghalaya') RETURNING id INTO state_21_id;
    INSERT INTO public.states (name) VALUES ('Mizoram') RETURNING id INTO state_22_id;
    INSERT INTO public.states (name) VALUES ('Nagaland') RETURNING id INTO state_23_id;
    INSERT INTO public.states (name) VALUES ('Odisha') RETURNING id INTO state_24_id;
    INSERT INTO public.states (name) VALUES ('Puducherry (UT)') RETURNING id INTO state_25_id;
    INSERT INTO public.states (name) VALUES ('Punjab') RETURNING id INTO state_26_id;
    INSERT INTO public.states (name) VALUES ('Rajasthan') RETURNING id INTO state_27_id;
    INSERT INTO public.states (name) VALUES ('Sikkim') RETURNING id INTO state_28_id;
    INSERT INTO public.states (name) VALUES ('Tamil Nadu') RETURNING id INTO state_29_id;
    INSERT INTO public.states (name) VALUES ('Telangana') RETURNING id INTO state_30_id;
    INSERT INTO public.states (name) VALUES ('Tripura') RETURNING id INTO state_31_id;
    INSERT INTO public.states (name) VALUES ('Uttarakhand') RETURNING id INTO state_32_id;
    INSERT INTO public.states (name) VALUES ('Uttar Pradesh') RETURNING id INTO state_33_id;
    INSERT INTO public.states (name) VALUES ('West Bengal') RETURNING id INTO state_34_id;

    -- Insert districts
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_0_id, 'Anantapur'),
        (state_0_id, 'Chittoor'),
        (state_0_id, 'East Godavari'),
        (state_0_id, 'Guntur'),
        (state_0_id, 'Krishna'),
        (state_0_id, 'Kurnool'),
        (state_0_id, 'Nellore'),
        (state_0_id, 'Prakasam'),
        (state_0_id, 'Srikakulam'),
        (state_0_id, 'Visakhapatnam'),
        (state_0_id, 'Vizianagaram'),
        (state_0_id, 'West Godavari'),
        (state_0_id, 'YSR Kadapa');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_1_id, 'Tawang'),
        (state_1_id, 'West Kameng'),
        (state_1_id, 'East Kameng'),
        (state_1_id, 'Papum Pare'),
        (state_1_id, 'Kurung Kumey'),
        (state_1_id, 'Kra Daadi'),
        (state_1_id, 'Lower Subansiri'),
        (state_1_id, 'Upper Subansiri'),
        (state_1_id, 'West Siang'),
        (state_1_id, 'East Siang'),
        (state_1_id, 'Siang'),
        (state_1_id, 'Upper Siang'),
        (state_1_id, 'Lower Siang'),
        (state_1_id, 'Lower Dibang Valley'),
        (state_1_id, 'Dibang Valley'),
        (state_1_id, 'Anjaw'),
        (state_1_id, 'Lohit'),
        (state_1_id, 'Namsai'),
        (state_1_id, 'Changlang'),
        (state_1_id, 'Tirap'),
        (state_1_id, 'Longding');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_2_id, 'Baksa'),
        (state_2_id, 'Barpeta'),
        (state_2_id, 'Biswanath'),
        (state_2_id, 'Bongaigaon'),
        (state_2_id, 'Cachar'),
        (state_2_id, 'Charaideo'),
        (state_2_id, 'Chirang'),
        (state_2_id, 'Darrang'),
        (state_2_id, 'Dhemaji'),
        (state_2_id, 'Dhubri'),
        (state_2_id, 'Dibrugarh'),
        (state_2_id, 'Goalpara'),
        (state_2_id, 'Golaghat'),
        (state_2_id, 'Hailakandi'),
        (state_2_id, 'Hojai'),
        (state_2_id, 'Jorhat'),
        (state_2_id, 'Kamrup Metropolitan'),
        (state_2_id, 'Kamrup'),
        (state_2_id, 'Karbi Anglong'),
        (state_2_id, 'Karimganj'),
        (state_2_id, 'Kokrajhar'),
        (state_2_id, 'Lakhimpur'),
        (state_2_id, 'Majuli'),
        (state_2_id, 'Morigaon'),
        (state_2_id, 'Nagaon'),
        (state_2_id, 'Nalbari'),
        (state_2_id, 'Dima Hasao'),
        (state_2_id, 'Sivasagar'),
        (state_2_id, 'Sonitpur'),
        (state_2_id, 'South Salmara-Mankachar'),
        (state_2_id, 'Tinsukia'),
        (state_2_id, 'Udalguri'),
        (state_2_id, 'West Karbi Anglong');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_3_id, 'Araria'),
        (state_3_id, 'Arwal'),
        (state_3_id, 'Aurangabad'),
        (state_3_id, 'Banka'),
        (state_3_id, 'Begusarai'),
        (state_3_id, 'Bhagalpur'),
        (state_3_id, 'Bhojpur'),
        (state_3_id, 'Buxar'),
        (state_3_id, 'Darbhanga'),
        (state_3_id, 'East Champaran (Motihari)'),
        (state_3_id, 'Gaya'),
        (state_3_id, 'Gopalganj'),
        (state_3_id, 'Jamui'),
        (state_3_id, 'Jehanabad'),
        (state_3_id, 'Kaimur (Bhabua)'),
        (state_3_id, 'Katihar'),
        (state_3_id, 'Khagaria'),
        (state_3_id, 'Kishanganj'),
        (state_3_id, 'Lakhisarai'),
        (state_3_id, 'Madhepura'),
        (state_3_id, 'Madhubani'),
        (state_3_id, 'Munger (Monghyr)'),
        (state_3_id, 'Muzaffarpur'),
        (state_3_id, 'Nalanda'),
        (state_3_id, 'Nawada'),
        (state_3_id, 'Patna'),
        (state_3_id, 'Purnia (Purnea)'),
        (state_3_id, 'Rohtas'),
        (state_3_id, 'Saharsa'),
        (state_3_id, 'Samastipur'),
        (state_3_id, 'Saran'),
        (state_3_id, 'Sheikhpura'),
        (state_3_id, 'Sheohar'),
        (state_3_id, 'Sitamarhi'),
        (state_3_id, 'Siwan'),
        (state_3_id, 'Supaul'),
        (state_3_id, 'Vaishali'),
        (state_3_id, 'West Champaran');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_4_id, 'Chandigarh');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_5_id, 'Balod'),
        (state_5_id, 'Baloda Bazar'),
        (state_5_id, 'Balrampur'),
        (state_5_id, 'Bastar'),
        (state_5_id, 'Bemetara'),
        (state_5_id, 'Bijapur'),
        (state_5_id, 'Bilaspur'),
        (state_5_id, 'Dantewada (South Bastar)'),
        (state_5_id, 'Dhamtari'),
        (state_5_id, 'Durg'),
        (state_5_id, 'Gariyaband'),
        (state_5_id, 'Janjgir-Champa'),
        (state_5_id, 'Jashpur'),
        (state_5_id, 'Kabirdham (Kawardha)'),
        (state_5_id, 'Kanker (North Bastar)'),
        (state_5_id, 'Kondagaon'),
        (state_5_id, 'Korba'),
        (state_5_id, 'Korea (Koriya)'),
        (state_5_id, 'Mahasamund'),
        (state_5_id, 'Mungeli'),
        (state_5_id, 'Narayanpur'),
        (state_5_id, 'Raigarh'),
        (state_5_id, 'Raipur'),
        (state_5_id, 'Rajnandgaon'),
        (state_5_id, 'Sukma'),
        (state_5_id, 'Surajpur  '),
        (state_5_id, 'Surguja');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_6_id, 'Dadra & Nagar Haveli');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_7_id, 'Daman'),
        (state_7_id, 'Diu');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_8_id, 'Central Delhi'),
        (state_8_id, 'East Delhi'),
        (state_8_id, 'New Delhi'),
        (state_8_id, 'North Delhi'),
        (state_8_id, 'North East  Delhi'),
        (state_8_id, 'North West  Delhi'),
        (state_8_id, 'Shahdara'),
        (state_8_id, 'South Delhi'),
        (state_8_id, 'South East Delhi'),
        (state_8_id, 'South West  Delhi'),
        (state_8_id, 'West Delhi');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_9_id, 'North Goa'),
        (state_9_id, 'South Goa');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_10_id, 'Ahmedabad'),
        (state_10_id, 'Amreli'),
        (state_10_id, 'Anand'),
        (state_10_id, 'Aravalli'),
        (state_10_id, 'Banaskantha (Palanpur)'),
        (state_10_id, 'Bharuch'),
        (state_10_id, 'Bhavnagar'),
        (state_10_id, 'Botad'),
        (state_10_id, 'Chhota Udepur'),
        (state_10_id, 'Dahod'),
        (state_10_id, 'Dangs (Ahwa)'),
        (state_10_id, 'Devbhoomi Dwarka'),
        (state_10_id, 'Gandhinagar'),
        (state_10_id, 'Gir Somnath'),
        (state_10_id, 'Jamnagar'),
        (state_10_id, 'Junagadh'),
        (state_10_id, 'Kachchh'),
        (state_10_id, 'Kheda (Nadiad)'),
        (state_10_id, 'Mahisagar'),
        (state_10_id, 'Mehsana'),
        (state_10_id, 'Morbi'),
        (state_10_id, 'Narmada (Rajpipla)'),
        (state_10_id, 'Navsari'),
        (state_10_id, 'Panchmahal (Godhra)'),
        (state_10_id, 'Patan'),
        (state_10_id, 'Porbandar'),
        (state_10_id, 'Rajkot'),
        (state_10_id, 'Sabarkantha (Himmatnagar)'),
        (state_10_id, 'Surat'),
        (state_10_id, 'Surendranagar'),
        (state_10_id, 'Tapi (Vyara)'),
        (state_10_id, 'Vadodara'),
        (state_10_id, 'Valsad');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_11_id, 'Ambala'),
        (state_11_id, 'Bhiwani'),
        (state_11_id, 'Charkhi Dadri'),
        (state_11_id, 'Faridabad'),
        (state_11_id, 'Fatehabad'),
        (state_11_id, 'Gurgaon'),
        (state_11_id, 'Hisar'),
        (state_11_id, 'Jhajjar'),
        (state_11_id, 'Jind'),
        (state_11_id, 'Kaithal'),
        (state_11_id, 'Karnal'),
        (state_11_id, 'Kurukshetra'),
        (state_11_id, 'Mahendragarh'),
        (state_11_id, 'Mewat'),
        (state_11_id, 'Palwal'),
        (state_11_id, 'Panchkula'),
        (state_11_id, 'Panipat'),
        (state_11_id, 'Rewari'),
        (state_11_id, 'Rohtak'),
        (state_11_id, 'Sirsa'),
        (state_11_id, 'Sonipat'),
        (state_11_id, 'Yamunanagar');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_12_id, 'Bilaspur'),
        (state_12_id, 'Chamba'),
        (state_12_id, 'Hamirpur'),
        (state_12_id, 'Kangra'),
        (state_12_id, 'Kinnaur'),
        (state_12_id, 'Kullu'),
        (state_12_id, 'Lahaul &amp; Spiti'),
        (state_12_id, 'Mandi'),
        (state_12_id, 'Shimla'),
        (state_12_id, 'Sirmaur (Sirmour)'),
        (state_12_id, 'Solan'),
        (state_12_id, 'Una');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_13_id, 'Anantnag'),
        (state_13_id, 'Bandipore'),
        (state_13_id, 'Baramulla'),
        (state_13_id, 'Budgam'),
        (state_13_id, 'Doda'),
        (state_13_id, 'Ganderbal'),
        (state_13_id, 'Jammu'),
        (state_13_id, 'Kargil'),
        (state_13_id, 'Kathua'),
        (state_13_id, 'Kishtwar'),
        (state_13_id, 'Kulgam'),
        (state_13_id, 'Kupwara'),
        (state_13_id, 'Leh'),
        (state_13_id, 'Poonch'),
        (state_13_id, 'Pulwama'),
        (state_13_id, 'Rajouri'),
        (state_13_id, 'Ramban'),
        (state_13_id, 'Reasi'),
        (state_13_id, 'Samba'),
        (state_13_id, 'Shopian'),
        (state_13_id, 'Srinagar'),
        (state_13_id, 'Udhampur');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_14_id, 'Bokaro'),
        (state_14_id, 'Chatra'),
        (state_14_id, 'Deoghar'),
        (state_14_id, 'Dhanbad'),
        (state_14_id, 'Dumka'),
        (state_14_id, 'East Singhbhum'),
        (state_14_id, 'Garhwa'),
        (state_14_id, 'Giridih'),
        (state_14_id, 'Godda'),
        (state_14_id, 'Gumla'),
        (state_14_id, 'Hazaribag'),
        (state_14_id, 'Jamtara'),
        (state_14_id, 'Khunti'),
        (state_14_id, 'Koderma'),
        (state_14_id, 'Latehar'),
        (state_14_id, 'Lohardaga'),
        (state_14_id, 'Pakur'),
        (state_14_id, 'Palamu'),
        (state_14_id, 'Ramgarh'),
        (state_14_id, 'Ranchi'),
        (state_14_id, 'Sahibganj'),
        (state_14_id, 'Seraikela-Kharsawan'),
        (state_14_id, 'Simdega'),
        (state_14_id, 'West Singhbhum');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_15_id, 'Bagalkot'),
        (state_15_id, 'Ballari (Bellary)'),
        (state_15_id, 'Belagavi (Belgaum)'),
        (state_15_id, 'Bengaluru (Bangalore) Rural'),
        (state_15_id, 'Bengaluru (Bangalore) Urban'),
        (state_15_id, 'Bidar'),
        (state_15_id, 'Chamarajanagar'),
        (state_15_id, 'Chikballapur'),
        (state_15_id, 'Chikkamagaluru (Chikmagalur)'),
        (state_15_id, 'Chitradurga'),
        (state_15_id, 'Dakshina Kannada'),
        (state_15_id, 'Davangere'),
        (state_15_id, 'Dharwad'),
        (state_15_id, 'Gadag'),
        (state_15_id, 'Hassan'),
        (state_15_id, 'Haveri'),
        (state_15_id, 'Kalaburagi (Gulbarga)'),
        (state_15_id, 'Kodagu'),
        (state_15_id, 'Kolar'),
        (state_15_id, 'Koppal'),
        (state_15_id, 'Mandya'),
        (state_15_id, 'Mysuru (Mysore)'),
        (state_15_id, 'Raichur'),
        (state_15_id, 'Ramanagara'),
        (state_15_id, 'Shivamogga (Shimoga)'),
        (state_15_id, 'Tumakuru (Tumkur)'),
        (state_15_id, 'Udupi'),
        (state_15_id, 'Uttara Kannada (Karwar)'),
        (state_15_id, 'Vijayapura (Bijapur)'),
        (state_15_id, 'Yadgir');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_16_id, 'Alappuzha'),
        (state_16_id, 'Ernakulam'),
        (state_16_id, 'Idukki'),
        (state_16_id, 'Kannur'),
        (state_16_id, 'Kasaragod'),
        (state_16_id, 'Kollam'),
        (state_16_id, 'Kottayam'),
        (state_16_id, 'Kozhikode'),
        (state_16_id, 'Malappuram'),
        (state_16_id, 'Palakkad'),
        (state_16_id, 'Pathanamthitta'),
        (state_16_id, 'Thiruvananthapuram'),
        (state_16_id, 'Thrissur'),
        (state_16_id, 'Wayanad');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_17_id, 'Agatti'),
        (state_17_id, 'Amini'),
        (state_17_id, 'Androth'),
        (state_17_id, 'Bithra'),
        (state_17_id, 'Chethlath'),
        (state_17_id, 'Kavaratti'),
        (state_17_id, 'Kadmath'),
        (state_17_id, 'Kalpeni'),
        (state_17_id, 'Kilthan'),
        (state_17_id, 'Minicoy');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_18_id, 'Agar Malwa'),
        (state_18_id, 'Alirajpur'),
        (state_18_id, 'Anuppur'),
        (state_18_id, 'Ashoknagar'),
        (state_18_id, 'Balaghat'),
        (state_18_id, 'Barwani'),
        (state_18_id, 'Betul'),
        (state_18_id, 'Bhind'),
        (state_18_id, 'Bhopal'),
        (state_18_id, 'Burhanpur'),
        (state_18_id, 'Chhatarpur'),
        (state_18_id, 'Chhindwara'),
        (state_18_id, 'Damoh'),
        (state_18_id, 'Datia'),
        (state_18_id, 'Dewas'),
        (state_18_id, 'Dhar'),
        (state_18_id, 'Dindori'),
        (state_18_id, 'Guna'),
        (state_18_id, 'Gwalior'),
        (state_18_id, 'Harda'),
        (state_18_id, 'Hoshangabad'),
        (state_18_id, 'Indore'),
        (state_18_id, 'Jabalpur'),
        (state_18_id, 'Jhabua'),
        (state_18_id, 'Katni'),
        (state_18_id, 'Khandwa'),
        (state_18_id, 'Khargone'),
        (state_18_id, 'Mandla'),
        (state_18_id, 'Mandsaur'),
        (state_18_id, 'Morena'),
        (state_18_id, 'Narsinghpur'),
        (state_18_id, 'Neemuch'),
        (state_18_id, 'Panna'),
        (state_18_id, 'Raisen'),
        (state_18_id, 'Rajgarh'),
        (state_18_id, 'Ratlam'),
        (state_18_id, 'Rewa'),
        (state_18_id, 'Sagar'),
        (state_18_id, 'Satna'),
        (state_18_id, 'Sehore'),
        (state_18_id, 'Seoni'),
        (state_18_id, 'Shahdol'),
        (state_18_id, 'Shajapur'),
        (state_18_id, 'Sheopur'),
        (state_18_id, 'Shivpuri'),
        (state_18_id, 'Sidhi'),
        (state_18_id, 'Singrauli'),
        (state_18_id, 'Tikamgarh'),
        (state_18_id, 'Ujjain'),
        (state_18_id, 'Umaria'),
        (state_18_id, 'Vidisha');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_19_id, 'Ahmednagar'),
        (state_19_id, 'Akola'),
        (state_19_id, 'Amravati'),
        (state_19_id, 'Aurangabad'),
        (state_19_id, 'Beed'),
        (state_19_id, 'Bhandara'),
        (state_19_id, 'Buldhana'),
        (state_19_id, 'Chandrapur'),
        (state_19_id, 'Dhule'),
        (state_19_id, 'Gadchiroli'),
        (state_19_id, 'Gondia'),
        (state_19_id, 'Hingoli'),
        (state_19_id, 'Jalgaon'),
        (state_19_id, 'Jalna'),
        (state_19_id, 'Kolhapur'),
        (state_19_id, 'Latur'),
        (state_19_id, 'Mumbai City'),
        (state_19_id, 'Mumbai Suburban'),
        (state_19_id, 'Nagpur'),
        (state_19_id, 'Nanded'),
        (state_19_id, 'Nandurbar'),
        (state_19_id, 'Nashik'),
        (state_19_id, 'Osmanabad'),
        (state_19_id, 'Palghar'),
        (state_19_id, 'Parbhani'),
        (state_19_id, 'Pune'),
        (state_19_id, 'Raigad'),
        (state_19_id, 'Ratnagiri'),
        (state_19_id, 'Sangli'),
        (state_19_id, 'Satara'),
        (state_19_id, 'Sindhudurg'),
        (state_19_id, 'Solapur'),
        (state_19_id, 'Thane'),
        (state_19_id, 'Wardha'),
        (state_19_id, 'Washim'),
        (state_19_id, 'Yavatmal');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_20_id, 'Bishnupur'),
        (state_20_id, 'Chandel'),
        (state_20_id, 'Churachandpur'),
        (state_20_id, 'Imphal East'),
        (state_20_id, 'Imphal West'),
        (state_20_id, 'Jiribam'),
        (state_20_id, 'Kakching'),
        (state_20_id, 'Kamjong'),
        (state_20_id, 'Kangpokpi'),
        (state_20_id, 'Noney'),
        (state_20_id, 'Pherzawl'),
        (state_20_id, 'Senapati'),
        (state_20_id, 'Tamenglong'),
        (state_20_id, 'Tengnoupal'),
        (state_20_id, 'Thoubal'),
        (state_20_id, 'Ukhrul');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_21_id, 'East Garo Hills'),
        (state_21_id, 'East Jaintia Hills'),
        (state_21_id, 'East Khasi Hills'),
        (state_21_id, 'North Garo Hills'),
        (state_21_id, 'Ri Bhoi'),
        (state_21_id, 'South Garo Hills'),
        (state_21_id, 'South West Garo Hills '),
        (state_21_id, 'South West Khasi Hills'),
        (state_21_id, 'West Garo Hills'),
        (state_21_id, 'West Jaintia Hills'),
        (state_21_id, 'West Khasi Hills');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_22_id, 'Aizawl'),
        (state_22_id, 'Champhai'),
        (state_22_id, 'Kolasib'),
        (state_22_id, 'Lawngtlai'),
        (state_22_id, 'Lunglei'),
        (state_22_id, 'Mamit'),
        (state_22_id, 'Saiha'),
        (state_22_id, 'Serchhip');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_23_id, 'Dimapur'),
        (state_23_id, 'Kiphire'),
        (state_23_id, 'Kohima'),
        (state_23_id, 'Longleng'),
        (state_23_id, 'Mokokchung'),
        (state_23_id, 'Mon'),
        (state_23_id, 'Peren'),
        (state_23_id, 'Phek'),
        (state_23_id, 'Tuensang'),
        (state_23_id, 'Wokha'),
        (state_23_id, 'Zunheboto');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_24_id, 'Angul'),
        (state_24_id, 'Balangir'),
        (state_24_id, 'Balasore'),
        (state_24_id, 'Bargarh'),
        (state_24_id, 'Bhadrak'),
        (state_24_id, 'Boudh'),
        (state_24_id, 'Cuttack'),
        (state_24_id, 'Deogarh'),
        (state_24_id, 'Dhenkanal'),
        (state_24_id, 'Gajapati'),
        (state_24_id, 'Ganjam'),
        (state_24_id, 'Jagatsinghapur'),
        (state_24_id, 'Jajpur'),
        (state_24_id, 'Jharsuguda'),
        (state_24_id, 'Kalahandi'),
        (state_24_id, 'Kandhamal'),
        (state_24_id, 'Kendrapara'),
        (state_24_id, 'Kendujhar (Keonjhar)'),
        (state_24_id, 'Khordha'),
        (state_24_id, 'Koraput'),
        (state_24_id, 'Malkangiri'),
        (state_24_id, 'Mayurbhanj'),
        (state_24_id, 'Nabarangpur'),
        (state_24_id, 'Nayagarh'),
        (state_24_id, 'Nuapada'),
        (state_24_id, 'Puri'),
        (state_24_id, 'Rayagada'),
        (state_24_id, 'Sambalpur'),
        (state_24_id, 'Sonepur'),
        (state_24_id, 'Sundargarh');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_25_id, 'Karaikal'),
        (state_25_id, 'Mahe'),
        (state_25_id, 'Pondicherry'),
        (state_25_id, 'Yanam');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_26_id, 'Amritsar'),
        (state_26_id, 'Barnala'),
        (state_26_id, 'Bathinda'),
        (state_26_id, 'Faridkot'),
        (state_26_id, 'Fatehgarh Sahib'),
        (state_26_id, 'Fazilka'),
        (state_26_id, 'Ferozepur'),
        (state_26_id, 'Gurdaspur'),
        (state_26_id, 'Hoshiarpur'),
        (state_26_id, 'Jalandhar'),
        (state_26_id, 'Kapurthala'),
        (state_26_id, 'Ludhiana'),
        (state_26_id, 'Mansa'),
        (state_26_id, 'Moga'),
        (state_26_id, 'Muktsar'),
        (state_26_id, 'Nawanshahr (Shahid Bhagat Singh Nagar)'),
        (state_26_id, 'Pathankot'),
        (state_26_id, 'Patiala'),
        (state_26_id, 'Rupnagar'),
        (state_26_id, 'Sahibzada Ajit Singh Nagar (Mohali)'),
        (state_26_id, 'Sangrur'),
        (state_26_id, 'Tarn Taran');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_27_id, 'Ajmer'),
        (state_27_id, 'Alwar'),
        (state_27_id, 'Banswara'),
        (state_27_id, 'Baran'),
        (state_27_id, 'Barmer'),
        (state_27_id, 'Bharatpur'),
        (state_27_id, 'Bhilwara'),
        (state_27_id, 'Bikaner'),
        (state_27_id, 'Bundi'),
        (state_27_id, 'Chittorgarh'),
        (state_27_id, 'Churu'),
        (state_27_id, 'Dausa'),
        (state_27_id, 'Dholpur'),
        (state_27_id, 'Dungarpur'),
        (state_27_id, 'Hanumangarh'),
        (state_27_id, 'Jaipur'),
        (state_27_id, 'Jaisalmer'),
        (state_27_id, 'Jalore'),
        (state_27_id, 'Jhalawar'),
        (state_27_id, 'Jhunjhunu'),
        (state_27_id, 'Jodhpur'),
        (state_27_id, 'Karauli'),
        (state_27_id, 'Kota'),
        (state_27_id, 'Nagaur'),
        (state_27_id, 'Pali'),
        (state_27_id, 'Pratapgarh'),
        (state_27_id, 'Rajsamand'),
        (state_27_id, 'Sawai Madhopur'),
        (state_27_id, 'Sikar'),
        (state_27_id, 'Sirohi'),
        (state_27_id, 'Sri Ganganagar'),
        (state_27_id, 'Tonk'),
        (state_27_id, 'Udaipur');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_28_id, 'East Sikkim'),
        (state_28_id, 'North Sikkim'),
        (state_28_id, 'South Sikkim'),
        (state_28_id, 'West Sikkim');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_29_id, 'Ariyalur'),
        (state_29_id, 'Chennai'),
        (state_29_id, 'Coimbatore'),
        (state_29_id, 'Cuddalore'),
        (state_29_id, 'Dharmapuri'),
        (state_29_id, 'Dindigul'),
        (state_29_id, 'Erode'),
        (state_29_id, 'Kanchipuram'),
        (state_29_id, 'Kanyakumari'),
        (state_29_id, 'Karur'),
        (state_29_id, 'Krishnagiri'),
        (state_29_id, 'Madurai'),
        (state_29_id, 'Nagapattinam'),
        (state_29_id, 'Namakkal'),
        (state_29_id, 'Nilgiris'),
        (state_29_id, 'Perambalur'),
        (state_29_id, 'Pudukkottai'),
        (state_29_id, 'Ramanathapuram'),
        (state_29_id, 'Salem'),
        (state_29_id, 'Sivaganga'),
        (state_29_id, 'Thanjavur'),
        (state_29_id, 'Theni'),
        (state_29_id, 'Thoothukudi (Tuticorin)'),
        (state_29_id, 'Tiruchirappalli'),
        (state_29_id, 'Tirunelveli'),
        (state_29_id, 'Tiruppur'),
        (state_29_id, 'Tiruvallur'),
        (state_29_id, 'Tiruvannamalai'),
        (state_29_id, 'Tiruvarur'),
        (state_29_id, 'Vellore'),
        (state_29_id, 'Viluppuram'),
        (state_29_id, 'Virudhunagar');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_30_id, 'Adilabad'),
        (state_30_id, 'Bhadradri Kothagudem'),
        (state_30_id, 'Hyderabad'),
        (state_30_id, 'Jagtial'),
        (state_30_id, 'Jangaon'),
        (state_30_id, 'Jayashankar Bhoopalpally'),
        (state_30_id, 'Jogulamba Gadwal'),
        (state_30_id, 'Kamareddy'),
        (state_30_id, 'Karimnagar'),
        (state_30_id, 'Khammam'),
        (state_30_id, 'Komaram Bheem Asifabad'),
        (state_30_id, 'Mahabubabad'),
        (state_30_id, 'Mahabubnagar'),
        (state_30_id, 'Mancherial'),
        (state_30_id, 'Medak'),
        (state_30_id, 'Medchal'),
        (state_30_id, 'Nagarkurnool'),
        (state_30_id, 'Nalgonda'),
        (state_30_id, 'Nirmal'),
        (state_30_id, 'Nizamabad'),
        (state_30_id, 'Peddapalli'),
        (state_30_id, 'Rajanna Sircilla'),
        (state_30_id, 'Rangareddy'),
        (state_30_id, 'Sangareddy'),
        (state_30_id, 'Siddipet'),
        (state_30_id, 'Suryapet'),
        (state_30_id, 'Vikarabad'),
        (state_30_id, 'Wanaparthy'),
        (state_30_id, 'Warangal (Rural)'),
        (state_30_id, 'Warangal (Urban)'),
        (state_30_id, 'Yadadri Bhuvanagiri');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_31_id, 'Dhalai'),
        (state_31_id, 'Gomati'),
        (state_31_id, 'Khowai'),
        (state_31_id, 'North Tripura'),
        (state_31_id, 'Sepahijala'),
        (state_31_id, 'South Tripura'),
        (state_31_id, 'Unakoti'),
        (state_31_id, 'West Tripura');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_32_id, 'Almora'),
        (state_32_id, 'Bageshwar'),
        (state_32_id, 'Chamoli'),
        (state_32_id, 'Champawat'),
        (state_32_id, 'Dehradun'),
        (state_32_id, 'Haridwar'),
        (state_32_id, 'Nainital'),
        (state_32_id, 'Pauri Garhwal'),
        (state_32_id, 'Pithoragarh'),
        (state_32_id, 'Rudraprayag'),
        (state_32_id, 'Tehri Garhwal'),
        (state_32_id, 'Udham Singh Nagar'),
        (state_32_id, 'Uttarkashi');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_33_id, 'Agra'),
        (state_33_id, 'Aligarh'),
        (state_33_id, 'Allahabad'),
        (state_33_id, 'Ambedkar Nagar'),
        (state_33_id, 'Amethi (Chatrapati Sahuji Mahraj Nagar)'),
        (state_33_id, 'Amroha (J.P. Nagar)'),
        (state_33_id, 'Auraiya'),
        (state_33_id, 'Azamgarh'),
        (state_33_id, 'Baghpat'),
        (state_33_id, 'Bahraich'),
        (state_33_id, 'Ballia'),
        (state_33_id, 'Balrampur'),
        (state_33_id, 'Banda'),
        (state_33_id, 'Barabanki'),
        (state_33_id, 'Bareilly'),
        (state_33_id, 'Basti'),
        (state_33_id, 'Bhadohi'),
        (state_33_id, 'Bijnor'),
        (state_33_id, 'Budaun'),
        (state_33_id, 'Bulandshahr'),
        (state_33_id, 'Chandauli'),
        (state_33_id, 'Chitrakoot'),
        (state_33_id, 'Deoria'),
        (state_33_id, 'Etah'),
        (state_33_id, 'Etawah'),
        (state_33_id, 'Faizabad'),
        (state_33_id, 'Farrukhabad'),
        (state_33_id, 'Fatehpur'),
        (state_33_id, 'Firozabad'),
        (state_33_id, 'Gautam Buddha Nagar'),
        (state_33_id, 'Ghaziabad'),
        (state_33_id, 'Ghazipur'),
        (state_33_id, 'Gonda'),
        (state_33_id, 'Gorakhpur'),
        (state_33_id, 'Hamirpur'),
        (state_33_id, 'Hapur (Panchsheel Nagar)'),
        (state_33_id, 'Hardoi'),
        (state_33_id, 'Hathras'),
        (state_33_id, 'Jalaun'),
        (state_33_id, 'Jaunpur'),
        (state_33_id, 'Jhansi'),
        (state_33_id, 'Kannauj'),
        (state_33_id, 'Kanpur Dehat'),
        (state_33_id, 'Kanpur Nagar'),
        (state_33_id, 'Kanshiram Nagar (Kasganj)'),
        (state_33_id, 'Kaushambi'),
        (state_33_id, 'Kushinagar (Padrauna)'),
        (state_33_id, 'Lakhimpur - Kheri'),
        (state_33_id, 'Lalitpur'),
        (state_33_id, 'Lucknow'),
        (state_33_id, 'Maharajganj'),
        (state_33_id, 'Mahoba'),
        (state_33_id, 'Mainpuri'),
        (state_33_id, 'Mathura'),
        (state_33_id, 'Mau'),
        (state_33_id, 'Meerut'),
        (state_33_id, 'Mirzapur'),
        (state_33_id, 'Moradabad'),
        (state_33_id, 'Muzaffarnagar'),
        (state_33_id, 'Pilibhit'),
        (state_33_id, 'Pratapgarh'),
        (state_33_id, 'RaeBareli'),
        (state_33_id, 'Rampur'),
        (state_33_id, 'Saharanpur'),
        (state_33_id, 'Sambhal (Bhim Nagar)'),
        (state_33_id, 'Sant Kabir Nagar'),
        (state_33_id, 'Shahjahanpur'),
        (state_33_id, 'Shamali (Prabuddh Nagar)'),
        (state_33_id, 'Shravasti'),
        (state_33_id, 'Siddharth Nagar'),
        (state_33_id, 'Sitapur'),
        (state_33_id, 'Sonbhadra'),
        (state_33_id, 'Sultanpur'),
        (state_33_id, 'Unnao'),
        (state_33_id, 'Varanasi');
    INSERT INTO public.districts (state_id, name) VALUES 
        (state_34_id, 'Alipurduar'),
        (state_34_id, 'Bankura'),
        (state_34_id, 'Birbhum'),
        (state_34_id, 'Burdwan (Bardhaman)'),
        (state_34_id, 'Cooch Behar'),
        (state_34_id, 'Dakshin Dinajpur (South Dinajpur)'),
        (state_34_id, 'Darjeeling'),
        (state_34_id, 'Hooghly'),
        (state_34_id, 'Howrah'),
        (state_34_id, 'Jalpaiguri'),
        (state_34_id, 'Kalimpong'),
        (state_34_id, 'Kolkata'),
        (state_34_id, 'Malda'),
        (state_34_id, 'Murshidabad'),
        (state_34_id, 'Nadia'),
        (state_34_id, 'North 24 Parganas'),
        (state_34_id, 'Paschim Medinipur (West Medinipur)'),
        (state_34_id, 'Purba Medinipur (East Medinipur)'),
        (state_34_id, 'Purulia'),
        (state_34_id, 'South 24 Parganas'),
        (state_34_id, 'Uttar Dinajpur (North Dinajpur)');
END $$;
